function createfigure(yvector1, yvector2, yvector3)
%CREATEFIGURE(yvector1, yvector2, yvector3)
%  YVECTOR1:  bar yvector
%  YVECTOR2:  bar yvector
%  YVECTOR3:  bar yvector

%  Auto-generated by MATLAB on 24-Sep-2025 15:40:52

% Create figure
figure1 = figure('InvertHardcopy','off','Color',[1 1 1]);

% Create axes
axes1 = axes('Position',...
    [0.742115027829314 0.124826629680999 0.243970315398887 0.819694868238558]);
hold(axes1,'on');

% Create bar
barh(yvector1,'FaceColor',[0.2 0.4 0.6]);

% Create title
title('J_{pho}');

%box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',18,'FontWeight','bold','YTick',[1 2 3 4 5 6 7],...
    'YTickLabel',...
    {'T^{s}_{max}','T^{m}_{max}','K^{s}_{m}','K^{m}_{m}','K^{p}_{m}','\lambda_{21}','\lambda_{31}'});
% Create axes
axes2 = axes('Position',...
    [0.423933209647495 0.124826629680999 0.263450834879406 0.821081830790569]);
hold(axes2,'on');

% Create bar
barh(yvector2,'FaceColor',[0.2 0.4 0.6]);

% Create xlabel
xlabel('Normalized LSC  ','FontWeight','bold','FontSize',24);


% Create title
title(' J_{mal}');

%box(axes2,'on');
grid(axes2,'on');
hold(axes2,'off');
% Set the remaining axes properties
set(axes2,'FontSize',18,'FontWeight','bold','YTick',[1 2 3 4 5 6 7],...
    'YTickLabel',...
    {'T^{s}_{max}','T^{m}_{max}','K^{s}_{m}','K^{m}_{m}','K^{p}_{m}','\lambda_{21}','\lambda_{31}'});
% Create axes
axes3 = axes('Position',...
    [0.104920811848784 0.127383031161756 0.254710663961694 0.822512351564535]);
hold(axes3,'on');

% Create bar
barh(yvector3,'FaceColor',[0.2 0.4 0.6]);

% Create ylabel
ylabel('Parameters','FontWeight','bold','FontSize',24);


% Create title
title('J_{succ}');

%box(axes3,'on');
grid(axes3,'on');
hold(axes3,'off');
% Set the remaining axes properties
set(axes3,'FontSize',18,'FontWeight','bold','YTick',[1 2 3 4 5 6 7],...
    'YTickLabel',...
    {'T^{s}_{max}','T^{m}_{max}','K^{s}_{m}','K^{m}_{m}','K^{p}_{m}','\lambda_{21}','\lambda_{31}'});
% Create textbox
annotation(figure1,'textbox',...
    [0.0248888577729549 0.948375866851595 0.0596011131725417 0.0644937586685158],...
    'String',{'a)'},...
    'FontWeight','bold',...
    'FontSize',30,...
    'FitBoxToText','off',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.36660793534109 0.949762829403606 0.0605287569573284 0.0644937586685159],...
    'String','b)',...
    'FontWeight','bold',...
    'FontSize',30,...
    'FitBoxToText','off',...
    'EdgeColor','none');

% Create textbox
annotation(figure1,'textbox',...
    [0.694700178527673 0.948375866851595 0.0596011131725418 0.0644937586685158],...
    'String','c)',...
    'FontWeight','bold',...
    'FontSize',30,...
    'FitBoxToText','off',...
    'EdgeColor','none');

